{"id": "sdl2.error", "path": "E:\\python3\\Lib\\site-packages\\sdl2\\error.py", "mtime": 1501768511, "size": 846, "hash": "218e9bd3ec0c051116c50e9611f06590", "data_mtime": 1502380988, "dependencies": ["sdl2.dll", "builtins"], "suppressed": [], "child_modules": [], "options": {"follow_imports": "normal", "disallow_any": [], "ignore_missing_imports": true, "strict_optional": false, "disallow_untyped_calls": false, "ignore_errors": false, "warn_return_any": false, "platform": "win32", "strict_boolean": false, "quick_and_dirty": false, "show_none_errors": true, "check_untyped_defs": false, "disallow_untyped_defs": false, "no_implicit_optional": false, "strict_optional_whitelist": null, "warn_no_return": true}, "dep_prios": [5, 5], "interface_hash": "b1bdcb2610b118be7260fcc007f0cf94", "version_id": "0.521"}
